title: Nice to meet you!
author: Kuyheang
email: ux@kuyheang.com
description: > # this means to ignore newlines until "baseurl:"
 This blog is for talking about design and skincare.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
